name: Code Coverage

on:
  push:
    branches: [ 'master' ]
  pull_request:
    branches: [ 'master' ]

jobs:
  coverage:
      name: Code Coverage

      runs-on: macos-latest
      env:
        BUILD_WRAPPER_OUT_DIR: buildwrapper # Directory where build-wrapper output will be placed

      steps:
        - name: Checkout
          uses: actions/checkout@v2
          with:
            fetch-depth: 0

        - name: Run xcodebuild with tests
          run: xcodebuild -project OmiseSDK.xcodeproj/ -scheme OmiseSDK -derivedDataPath Build/ -destination 'platform=iOS Simulator,name=iPhone 11,OS=16.2' -enableCodeCoverage YES clean build test CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO

        - name: Convert Xcode coverage to SonarCloud format
          run: bash xccov-to-sonarqube-generic.sh build/Logs/Test/*.xcresult/ > sonarqube-generic-coverage.xml

        - name: Mark build directory as deletable
          run: xattr -w com.apple.xcode.CreatedByBuildSystem true ./build
          
        - name: Upload coverage report
          uses: actions/upload-artifact@v2
          with:
            path: sonarqube-generic-coverage.xml
            retention-days: 5 # Artifact will be available only for 5 days.

#        - name: Run build-wrapper
#          run: |
#              build-wrapper-macosx-x86 --out-dir ${{ env.BUILD_WRAPPER_OUT_DIR }} xcodebuild clean build
#
#        - name: Dump build-wrapper
#          run: cat ./buildwrapper/build-wrapper-dump.json
  
  sonar-scan:    
      name: Sonar scan
      runs-on: ubuntu-latest
      steps:
        - name: Checkout
          uses: actions/checkout@v2
          with:
            fetch-depth: 0
          
        - uses: actions/download-artifact@master
          with:
            name: sonarqube-generic-coverage.xml
            path: ./
            
        - name: Run sonar-scanner
          uses: SonarSource/sonarcloud-github-action@master
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }} # Put the name of your token here
