name: CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run xcodebuild with tests
      run: xcodebuild test -scheme OmiseSDKTests -destination 'platform=iOS Simulator,name=iPhone 11,OS=latest' ENABLE_TESTABILITY=yes
